
version: "3.9"

services:
    mysqldb_ms:
        container_name: ${MSF_MYSQL_FORM_CREATE_NAME_CONTAINER}
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_ROOT_PASSWORD: ${MSF_MYSQL_FORM_CREATE_PASS}
            MYSQL_DATABASE: ${MSF_MYSQL_FORM_CREATE_DATABASE}
        ports:
         - ${MSF_MYSQL_FORM_CREATE_PORT}:3306
        #volumes:
        #  - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    rabbitmq_ms:
        image: rabbitmq:3.8-management
        container_name: ${MSF_RABBIT_NAME_CONTAINER}
        # volumes:
        # - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        # - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
        ports:
         - ${MSF_RABBIT_PORT}:5672
         - ${MSF_RABBIT_PORT_WEB}:15672
