
version: "3.9"

services:
    mysqldb_ms:
        container_name: mysqldb_ms
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "form-create"
        ports:
         - 3306:3306
        #volumes:
        #  - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    rabbitmq_ms:
        image: rabbitmq:3-management
        container_name: rabbitmq_ms
        volumes:
         - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
         - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
        ports:
         - 5672:5672
         - 15672:15672
